### ISSUE TITLE
Filter Topics

### ISSUE THREAD

**Issue by moserke** [danielqsj/kafka_exporter#1]
Reading through the code it doesn't appear that you can filter which topics. Is this possible?

If not, would be nice to be able to do a regex based filter on topics.  This would allow for places where "multi-tenancy" is happening in the broker to allow for collecting metrics on only the topics that we are interested in.

Without this the amount of metrics collected is very large.

**Comment by danielqsj** [comment]
Thanks, I will think about it in next release.

**Comment by danielqsj** [comment]
Fixed in fbcdb27c6c9cfb69c9d8dfd93ccbd9932afa3ea1.
