### ISSUE TITLE
kafka exporter should give the possibility to exclude topic

### ISSUE THREAD

**Issue by nicolasblaye** [danielqsj/kafka_exporter#103]
I tried to use kafka_exporter on my newly created kafka. We have 3 brokers with only a handful of consumers. Because of that, not every partition is used in the `__consumer_offsets` topic. When I try to get the metrics, it takes **a lot of time** because it tries to connect to every partition leader and fails for the empty one with 
```
ERRO[0081] Cannot get leader of topic __consumer_offsets partition 31: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.  source="kafka_exporter.go:275"
ERRO[0083] Cannot get current offset of topic __consumer_offsets partition 31: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.  source="kafka_exporter.go:284"
ERRO[0085] Cannot get oldest offset of topic __consumer_offsets partition 31: kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.  source="kafka_exporter.go:296"
```

I saw that we can filter topic we want to listen to, using a regex, so I tried `--topic.filter='^(?!__consumer_offsets).*$'`, but this is not go regex syntax so it failed with `invalid or unsupported Perl syntax: (?!`

It could be nice to instead have an exclusion mechanism, or to have a workaround for empty partition with no leader.

**Comment by danielqsj** [comment]
thanks, closed by https://github.com/danielqsj/kafka_exporter/pull/379
