### ISSUE TITLE
Please cut another release

### ISSUE THREAD

**Issue by anitakrueger** [danielqsj/kafka_exporter#117]
@danielqsj Could you cut another release by any chance please?

**Comment by stealth1188** [comment]
Any help on this is greatly appreciated. 
Require min of Sarama 1.23 or higher to support Kafka 2.3.0 or higher and Kerberos. 
Thank you in advance.

**Comment by AnandDevan** [comment]
I am also looking for zookeeper based offset tracking you have in master

**Comment by danielqsj** [comment]
Hi all, 1.3.0 was released. Hope to hear more feedback. Thanks.
