### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gmacgregor1** [danielqsj/kafka_exporter#124]
Figured i would see when the next release is planned for. 

I would like to use the zookeeper options that have been added, and we have a policy to not use master branches in our environments.

**Comment by anitakrueger** [comment]
I opened this a while ago as well: https://github.com/danielqsj/kafka_exporter/issues/117

I'm starting to think this project is dead :(

**Comment by danielqsj** [comment]
Hi  @gmacgregor1 @anitakrueger , sorry for late reply, I'm busy in other things for a while.
But this project is alive, and I plan to do a new release soon.

**Comment by beorn-** [comment]
@danielqsj if you need a bit of help just ask for it :)

**Comment by pint2oo** [comment]
Hi, 
Any updates on when the next release will be published ?
- pint2oo

**Comment by danielqsj** [comment]
Hi all, 1.3.0 was released. Hope to hear more feedback. Thanks.
