### ISSUE TITLE
I found current sarama version is not good to  support SaslAuthenticate.

### ISSUE THREAD

**Issue by Robin-up** [danielqsj/kafka_exporter#128]
I am considering to setup the exporter to monitor Kafka that is using SaslAuthenticate, but i found current sarama version is not good to  support SaslAuthenticate. Hope to upgrade @danielqsj :)

**Comment by sebco59** [comment]
Works for me with Kafka 2.3.0 and SASL Authenticate. Just try with `--tls.insecure-skip-tls-verify` and `--tls.enabled`

View my reply here: https://github.com/danielqsj/kafka_exporter/issues/116#issuecomment-559108062

**Comment by Robin-up** [comment]
> Works for me with Kafka 2.3.0 and SASL Authenticate. Just try with `--tls.insecure-skip-tls-verify` and `--tls.enabled`
> 
> View my reply here: [#116 (comment)](https://github.com/danielqsj/kafka_exporter/issues/116#issuecomment-559108062)

**Comment by Robin-up** [comment]
> Works for me with Kafka 2.3.0 and SASL Authenticate. Just try with `--tls.insecure-skip-tls-verify` and `--tls.enabled`
> 
> View my reply here: [#116 (comment)](https://github.com/danielqsj/kafka_exporter/issues/116#issuecomment-559108062)

I tried , but it doesn't work ......


NFO[0000] Starting kafka_exporter (version=1.2.0, branch=HEAD, revision=830660212e6c109e69dcb1cb58f5159fe3b38903)  source="kafka_exporter.go:474"
INFO[0000] Build context (go=go1.10.3, user=root@981cde178ac4, date=20180707-14:34:48)  source="kafka_exporter.go:475"
[sarama] 2019/12/03 02:56:03 Initializing new client
[sarama] 2019/12/03 02:56:03 client/metadata fetching metadata for all topics from broker xxxxxxxxxx:9093
[sarama] 2019/12/03 02:56:05 Connected to broker at xxxxxxxxxxxxx:9093 (unregistered)
[sarama] 2019/12/03 02:56:15 client/metadata got error from broker while fetching metadata: EOF
[sarama] 2019/12/03 02:56:15 Closed connection to broker xxxxxxxxxxxxxxx:9093
[sarama] 2019/12/03 02:56:15 client/metadata no available broker to send metadata request to
[sarama] 2019/12/03 02:56:15 client/brokers resurrecting 1 dead seed brokers
[sarama] 2019/12/03 02:56:15 client/metadata retrying after 250ms... (3 attempts remaining)
[sarama] 2019/12/03 02:56:15 client/metadata fetching metadata for all topics from broker xxxxxxxxxxxxxxxxxxxxx:9093
