### ISSUE TITLE
Is it possible to read kafka topic by using this exporter?

### ISSUE THREAD

**Issue by Kaali09** [danielqsj/kafka_exporter#136]
Hi, 

I have 2 kafka topics where my application is pushing some application related metrics in a json format. I have to send the metrics which is there in the kafka topic to prometheus. Is it possible with this exporter and how to do? Please suggest on this.

**Comment by pousa** [comment]
This exporter is about [kafka](https://kafka.apache.org/) related metrics only. What you are looking for is something like this [exporter](https://github.com/ogibayashi/kafka-topic-exporter); never used. Also have a look in telegraf input/outut plugins.

**Comment by Kaali09** [comment]
@pousa Thank you for the response. Had to write own exporter for my requirement.
