### ISSUE TITLE
拉取github的方式打docker images，exporter容器报下面的错误，直接拉取dockerhub的镜像,容器没有问题

### ISSUE THREAD

**Issue by dingyule** [danielqsj/kafka_exporter#158]
Error: failed to start container "kafka": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/bin/kafka_exporter\": permission denied": unknown

**Comment by dingyule** [comment]
找到问题了，可能是我编译的时候出现了问题- -

**Comment by jinleileiking** [comment]
@dingyule dockerfile有点问题，看我的fork。。。

**Comment by dingyule** [comment]
> @dingyule dockerfile有点问题，看我的fork。。。
我问题解决了，编译go代码出现的问题，不过感谢
