### ISSUE TITLE
Error: make: *** [Makefile:57: promu] Error 1

### ISSUE THREAD

**Issue by AliKhyar** [danielqsj/kafka_exporter#180]
while running `make crossbuild` in github actions to compile it returns this error

```
Error: make: *** [Makefile:57: promu] Error 1
!! The base builder docker image exited unexpectedly: exit status 

make: *** [crossbuild] Error 1
Error: Makefile:34: recipe for target 'crossbuild' failed
Error: Process completed with exit code 2.
```
any idea why it does so?

**Comment by dmitrievav** [comment]
Just a guess, it might be 

`/bin/promu: No such file or directory`

end to solve it you have to add somewhere

`export GOPATH=$(go env GOPATH)`
