### ISSUE TITLE
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

### ISSUE THREAD

**Issue by Hackeruncle** [danielqsj/kafka_exporter#20]
```
[root@hadoop001 kafka_exporter-1.0.1.linux-amd64]# ./kafka_exporter \
> --kafka.server=192.169.137.141:9092 \
> --kafka.server=192.169.137.142:9092 \
> --kafka.server=192.169.137.143:9092 
```
INFO[0000] Starting kafka_exporter (version=1.0.1, branch=HEAD, revision=f1639a649ebcfe11bce6782ab281a59d05b6d9e9)  source="kafka_exporter.go:432"
INFO[0000] Build context (go=go1.9.2, user=root@bc4118dc5bad, date=20180112-13:07:13)  source="kafka_exporter.go:433"

**Error Init Kafka Client
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)**

goroutine 1 [running]:
main.NewExporter(0xc42000ea80, 0x3, 0x4, 0x100, 0x8ea778, 0x0, 0x8ea778, 0x0, 0x0, 0x8ea778, ...)
        /go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:205 +0x92d
main.main()
        /go/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:439 +0x1d6c
[root@hadoop001 kafka_exporter-1.0.1.linux-amd64]#

**Comment by fmeeuw** [comment]
I am also experiencing the exact same issue, with kafka 0.10.1.0. Any thoughts on this one?

**Comment by epoll486** [comment]
看下你本机是否可以连通kafka的9092端口

**Comment by homer6** [comment]
I ran into this issue, too, but was able to resolve it.

I added 

    //verbose debugging (comment this line to disabled verbose sarama logging)
    sarama.Logger = log.New(os.Stdout, "[sarama] ", log.LstdFlags)

to enable the verbose logging. After which, it said that I was not including my port number in the connection string. I would have thought it would use the default kafka port, if unspecified, as rdkafka does, but samara requires the port to be explicitly set.

I actually left verbose logging on and was able to gain valuable information on another hard to diagnose issue. So, I've chosen to leave verbose logging on for production because it doesn't appear to be too verbose.

**Comment by danielqsj** [comment]
@Hackeruncle @homer6 You can pass param `log.enable-sarama = true` to enable sarama log. It will show detailed logs about kafka brokers connection.

**Comment by danielqsj** [comment]
No update for a long time, close it.

**Comment by nikita-clearscale** [comment]
faced with same issue.

I have run multiple docker images, publishing event works:

    kafka-console-producer.bat --broker-list 0.0.0.0:32783 --topic test

But whgen I try to start kafka_exporter I got en error:

    docker run -ti --rm -p 9308:9308 danielqsj/kafka-exporter --kafka.server=0.0.0.0:32783
    INFO[0000] Starting kafka_exporter (version=1.2.0, branch=HEAD, revision=56c1d47f9794d59d042852cc31558257e24d2ea0)  source="kafka_exporter.go:500"
    INFO[0000] Build context (go=go1.9, user=travis@travis-job-fa00a602-ae4f-4696-ac19-3ee24885c116, date=20190131-13:51:26)  source="kafka_exporter.go:501"
    ERRO[0000] Error Init Kafka Client                       source="kafka_exporter.go:184"
    panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

    goroutine 1 [running]:
    main.NewExporter(0xc42003fd40, 0x1, 0x1, 0x100, 0x96d438, 0x0, 0x96d438, 0x0, 0x0, 0x96d438, ...)
        /home/travis/gopath/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:185 +0xbbc
    main.main()
        /home/travis/gopath/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:606 +0x3aa7

Do not undersatand how to fix this :(
Could you please help or give a direction for fixing?

**Comment by snajdov** [comment]
Sarama logs this as:
```[sarama] 2019/04/30 20:44:39 Failed to connect to broker kafka:9092: dial tcp: lookup kafka on 8.8.8.8:53: no such host```
although I have a `127.0.0.1 kafka` mapping in `/etc/hosts` and it resolves correctly.

This means that the image handles the DNS itself communicating with the `8.8.8.8` DNS directly, instead of using the OS to do the job. This will cause a problem when using local DNS resolution techniques such as `/etc/hosts` mappings, or local DNS zonefiles.

Maybe something like this will help: https://github.com/golang/go/issues/22846

**Comment by Shubhamnegi** [comment]
Had a similar issue with filebeat. Fixed by adding a version parameter.  By default 0.10.0.0 is enabled

**Comment by GN01** [comment]
同样的报错，增加 --kafka.version=0.10.0.1 (我kafka的版本)。成功解决

**Comment by rodrigorodrigues** [comment]
Hi I was having similar issue could not resolve the hostname.


	E0317 23:18:59.377552       1 kafka_exporter.go:417] Cannot get current offset of topic __consumer_offsets partition 49: dial tcp: lookup kafka-broker0-745785c775-dmpzm on 10.152.183.10:53: no such host
	E0317 23:18:59.411527       1 kafka_exporter.go:429] Cannot get oldest offset of topic __consumer_offsets partition 49: dial tcp: lookup kafka-broker0-745785c775-dmpzm on 10.152.183.10:53: no such host
	I0317 23:18:59.411687       1 kafka_exporter.go:645] Fetching consumer group metrics
	E0317 23:18:59.425797       1 kafka_exporter.go:543] Cannot get consumer group: dial tcp: lookup kafka-broker0-745785c775-dmpzm on 10.152.183.10:53: no such host

Need to add the hostname manually in /etc/hosts

Is there some way to make that work without doing this manually? I'm using arm64 on Raspberry Pi 4.

**Comment by violet4795** [comment]
hi,
I also had a similar problem.
In my case I was using zookeeper,

I couldn't even write the zookeeper's address.
After that, it started to work by adding the kafka.version option.

I hope this helps.

`./kafka_exporter --kafka.server=localhost:9092 --zookeeper.server=localhost:2181 --kafka.version=0.8.2.2 &`

**Comment by GN01** [comment]
> hi, I also had a similar problem. In my case I was using zookeeper,
> 
> I couldn't even write the zookeeper's address. After that, it started to work by adding the kafka.version option.
> 
> I hope this helps.
> 
> `./kafka_exporter --kafka.server=localhost:9092 --zookeeper.server=localhost:2181 --kafka.version=0.8.2.2 &`


try user docker?
i try it is ok


docker run --name kafka_exporter_test  -p 49308:9308 --restart always -d danielqsj/kafka-exporter --kafka.server=yourserverip:6667 --kafka.server=yourserverip:6667 --kafka.server=yourserverip:6667 --zookeeper.server=yourserverip:2181 --zookeeper.server=yourserverip:2181 --zookeeper.server=yourserverip:2181 --kafka.version=0.10.0.1
