### ISSUE TITLE
New Release - Date?

### ISSUE THREAD

**Issue by krishvoor** [danielqsj/kafka_exporter#206]
Hi @danielqsj - I appreciate kafka-exporter and how useful this is across many products.
Do you plan to do a release sometime sooner ?

I see people have expressed several times #117 #124  which shows how important this is to larger audience.
We are eagerly awaiting to see a new release.

**Comment by danielqsj** [comment]
Hi all, 1.3.0 was released. Hope to hear more feedback. Thanks.

**Comment by krishvoor** [comment]
Hey @danielqsj - Thanks for publishing new release v1.3.0
However, I do not see architecture specific binaries under https://github.com/danielqsj/kafka_exporter/releases/tag/v1.3.0, is there a plan to do so ?

Additionally, ppc64le & s390x equivalent docker-images are not published [here](https://hub.docker.com/r/danielqsj/kafka-exporter/tags?page=1&ordering=last_updated) 
I can submit a PR specific CI/CD operations for the mentioned architectures.

**Comment by joancafom** [comment]
Hi! Any updates on the architecture-specific binaries for this new release?
