### ISSUE TITLE
Binaries missing in 1.3.0 release

### ISSUE THREAD

**Issue by rvgud** [danielqsj/kafka_exporter#219]
Can you please add the binaries in 1.3.0 release.

Thanks

**Comment by jonaz** [comment]
Duplicate of https://github.com/danielqsj/kafka_exporter/issues/218

**Comment by karlism** [comment]
Also duplicate of https://github.com/danielqsj/kafka_exporter/issues/211

**Comment by karlism** [comment]
Appears to be fixed in 1.3.1.

**Comment by danielqsj** [comment]
yes, I have fixed it in 1.3.1

**Comment by karlism** [comment]
Thanks!
