### ISSUE TITLE
Metrics Do Not Return Consumer Group Lag Time

### ISSUE THREAD

**Issue by RecursiveLooper1992** [danielqsj/kafka_exporter#22]
Hello,

My team really loves this project and we are very thankful that you wrote this.

We are seeing one slight issue where the exporter is not reporting on Consumer Group Lag Time.
Here are the metrics we are not seeing:

```
kafka_consumergroup_lag
kafka_consumergroup_current_offset
```

All of the other metrics listed in the README have been observed.

We are running this on Kubernetes 1.7 using the Docker image found in the documentation:
https://hub.docker.com/r/danielqsj/kafka-exporter/

Here is the version of the image that we are using:
danielqsj/kafka-exporter:1.0.1

The version of Kafka that we are using is 0.10.0.1.
We also tried an updated version of Kafka, at version 0.10.1.0 and still encountered the same issues.

Here is the command we are running when starting the container:

```
/bin/kafka_exporter --kafka.server=host1:9092 --kafka.server=host2:9092 --kafka.server=host3:9092 --log.enable-sarama --log.level=debug --topic.filter=(topic1|topic2)
```

We appreciate you taking a look into this issue, please let us know if we can provide any additional diagnostic information to solve this.

Thank You,
Matt

**Comment by kloba** [comment]
I am having the same problem on Kafka 1.0.1 (danielqsj/kafka-exporter:1.0.1).

**Comment by danielqsj** [comment]
@RecursiveLooper1992 @kloba Could you provide detailed logs?

**Comment by danielqsj** [comment]
@RecursiveLooper1992 @kloba 
v1.1.0 is released. Please try new image.

**Comment by danielqsj** [comment]
@RecursiveLooper1992 Glad to hear it.
