### ISSUE TITLE
Kafka Exporter stops reporting kafka_consumergroup_lag_* for specific topics

### ISSUE THREAD

**Issue by YuvalItzchakov** [danielqsj/kafka_exporter#226]
Hi,

kafka-exporter v1.3.1
Kubernetes v1.15.11
Kafka v2.8.0 (AWS MSK)

Recently, I have come across a few cases where a consumer stops reading data from a topic, and when searching for the metrics via kafka-exporter, they don't exist for that specific consumer, topic pair (although I can see the consumer lag using [Kafdrop](https://github.com/obsidiandynamics/kafdrop) for the given consumer group. Only once I restart the service that's registering under the consumergroup do I then see kafka-exporter reporting back the metrics for the consumergroup under that topic.

Has this happened to anyone?

**Comment by scholzj** [comment]
I can see the same (also Kafka 2.8.0, but not MSK). It now reports only consumer groups which have consumers online. Not sure if this is intentional feature, or a bug. But I think knowing the lag for consumer groups even when they do not have any consumers online is useful information.

**Comment by danielqsj** [comment]
#255 has been merged and v1.3.2 has been released, please have a try.

**Comment by scholzj** [comment]
Thanks a lot @danielqsj

**Comment by danielqsj** [comment]
V1.4.0 is released, the default behavior of consumer group offset is same as v1.3.0, please have a try.
