### ISSUE TITLE
Error: Cannot get GetMemberAssignment of group member

### ISSUE THREAD

**Issue by kmatsoukas** [danielqsj/kafka_exporter#227]
Hello,

Every time Prometheus scrapes the exporter, the exporter logs the error:

level=error msg="Cannot get GetMemberAssignment of group member &{GROUP_NAME xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx [....] []} : kafka: insufficient data to decode packet, more bytes expected" source="kafka_exporter.go:413"

Kafka version: 2.7.0

Any idea how to fix this?

**Comment by airwalk225** [comment]
Looks like this is a problem in the latest release `v1.3.1` we downgraded to `v1.3.0` and had no issues after that.

**Comment by drTr0jan** [comment]
There is the problem in `v1.3.2` also.

**Comment by danielqsj** [comment]
this is related to this change https://github.com/danielqsj/kafka_exporter/pull/220.
@iamgd67 please have a look~
