### ISSUE TITLE
Support for TLS

### ISSUE THREAD

**Issue by sam-celer** [danielqsj/kafka_exporter#231]
Is there any plan to start supporting TLS for the exporter web server so the metrics can be retrieved in an encrypted manner via https?
Currently using a proxy in the front but it would be nice to be able to connect directly.

Thanks

**Comment by edwin092** [comment]
I would be also interested in TLS enablement for the web server via https://pkg.go.dev/net/http#ListenAndServeTLS:
```
func ListenAndServeTLS(addr, certFile, keyFile string, handler Handler) error
```

A new flag could be added to enable/disable https.

@danielqsj thoughts?

**Comment by danielqsj** [comment]
@edwin092 Please go ahead, looking forward for the commit!

**Comment by danielqsj** [comment]
@edwin092 @sam-celer 1.4.2 was released, please have a try.

**Comment by sam-celer** [comment]
Trying to test this out but somehow the log.level command line option that used to work is not accepted anymore

kafka-exporter --web.listen-address=0.0.0.0:24012 --kafka.server=localhost:9092 --log.level=info
flag provided but not defined: -log.level

This flag is still valid according to kafka-exporter --help

**Comment by edwin092** [comment]
See https://github.com/danielqsj/kafka_exporter/issues/257. Just drop the option altogether.

**Comment by sam-celer** [comment]
Yeah I did. The option should be removed from the --help display for good measure.
On the TLS side of things, the new release seems to be working fine. Going to deploy this across our estate. Thanks for the efforts getting this implemented

**Comment by edwin092** [comment]
@sam-celer glad I could help!
