### ISSUE TITLE
ERRO[0025] Cannot get consumer group: dial tcp: lookup

### ISSUE THREAD

**Issue by yinhejianke** [danielqsj/kafka_exporter#248]
ERRO[0025] Cannot get consumer group: dial tcp: lookup

**Comment by yinhejianke** [comment]
怎么解决，prometheus一直那不多数据。图标显示，export一直报这个错

**Comment by danielqsj** [comment]
Check the connection with the configuration `kafka.server`

**Comment by yinhejianke** [comment]
找到问题了，解决了，是kafka本身的配置问题。跟export没关系。
