### ISSUE TITLE
消费组有堆积 但是metrics里没有收集到

### ISSUE THREAD

**Issue by Yu1132664358** [danielqsj/kafka_exporter#252]
如图 只能查到位移  lag完全查不到
https://sm.ms/image/M7y9agkKHvXGjFu
https://sm.ms/image/laP42SfcXsiV3rJ
https://sm.ms/image/z2nA3GXMYbxyUFT

**Comment by danielqsj** [comment]
https://github.com/danielqsj/kafka_exporter/pull/255 has been merged and v1.3.2 has been released, please have a try.

**Comment by danielqsj** [comment]
https://github.com/danielqsj/kafka_exporter/pull/255 has been merged and v1.3.2 has been released, please have a try.

**Comment by danielqsj** [comment]
V1.4.0 is released, the default behavior of consumer group offset is same as v1.3.0, please have a try.
