### ISSUE TITLE
error: unknown long flag '--log.level' in v1.3.2

### ISSUE THREAD

**Issue by edwin092** [danielqsj/kafka_exporter#257]
With **kafka_exporter v1.3.2** I get:
```
kafka_exporter: error: unknown long flag '--log.level'
```

It worked fine in **v1.3.1**.

**Comment by danielqsj** [comment]
sorry, we replaced the log dependency. @mihail-sky would you have interested in this fix ?

**Comment by danielqsj** [comment]
@edwin092 The new release v1.4.1 has introduce a new param `verbosity` to control the log level via glog.
