### ISSUE TITLE
Error: was collected before with the same name and label values

### ISSUE THREAD

**Issue by artful88533** [danielqsj/kafka_exporter#280]
Hello!
We have the next situation
One of the broker nodes has been crashed (replication factor 3). When we added a new clean node to the cluster, exporter started responding with an error
```
An error has occurred while serving metrics:

1 error(s) occurred:
* collected metric "kafka_consumergroup_members" { label:<name:"consumergroup" value:"spark_apac_bids-kafka" > gauge:<value:0 > } was collected before with the same name and label values
```

In the list, I see just one consumer group
```
kafka-consumer-groups.sh --bootstrap-server kafka-broker1.my.io:9091,kafka-broker2.my.io:9091,kafka-broker3.my.io:9091,kafka-broker4.my.io:9091 --list | grep bids
spark_apac_bids-kafka
```

For example, in kafka-manager https://hub.docker.com/r/vimagick/cmak all works fine without errors.

**Comment by fuping-han** [comment]
same issue to me，when i excute below shell command，it will response two same consumer group：
>kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --list
............
abc-group
abc-group
i cant understand whats different the two consumer groups。

**Comment by artful88533** [comment]
This exporter works fine https://github.com/lightbend/kafka-lag-exporter
