### ISSUE TITLE
Cannot get replicas and in-sync replicas of topic when I killed a kafka instance

### ISSUE THREAD

**Issue by LinuxGit** [danielqsj/kafka_exporter#31]
When I killed a kafka instace, kafka_exporter reported following error:
time="2018-05-08T16:00:00+08:00" level=error msg="Cannot get in-sync replicas of topic test partition 0: kafka server: Replica information not available, one or more brokers are down." source="kafka_exporter.go:312"
time="2018-05-08T16:00:00+08:00" level=error msg="Cannot get replicas of topic 6547921892168160511_192-168-1-88_8250 partition 0: kafka server: Replica information not available, one or more brokers are down." source="kafka_exporter.go:303"

The kafka cluster has three nodes, the other two nodes are alive, but there're no kafka_topic_partition_in_sync_replica and kafka_topic_partition_replicas metrics any more.

**Comment by julienmmm** [comment]
I am experiencing the same issue with the metrics kafka_topic_partition_under_replicated_partition

**Comment by LinuxGit** [comment]
@julienmmm I updated sarama to master branch to solve this issue.

**Comment by danielqsj** [comment]
@LinuxGit New image v1.2.0 has update the newest sarama release. Please have a try.
