### ISSUE TITLE
Kerberos authentification

### ISSUE THREAD

**Issue by maxtar** [danielqsj/kafka_exporter#33]
Hi,
I'm I right, that exporter doesn't support kerberos authentication? And no way use it?

**Comment by danielqsj** [comment]
@maxtar Thanks for your feedback.
Currently, kafka_exporter not support kerberos authentication because its dependency `sarama` not support kerberos authentication now. Refer https://github.com/Shopify/sarama/issues/934 .
When `sarama` support it, kafka_exporter will follow immediately.
