### ISSUE TITLE
Do not see any Consumer group or Lag information 

### ISSUE THREAD

**Issue by CodeWithAdarsha** [danielqsj/kafka_exporter#345]
I am using latest version of docker composer but didn't see , Can you please help me here , 

- kafka_consumergroup_lag

- kafka_consumergroup_current_offset

![image](https://user-images.githubusercontent.com/11813559/198065440-e2dba350-818c-4bad-a968-af6ccdc92ce6.png)

![image](https://user-images.githubusercontent.com/11813559/198066055-edde7cd1-1e07-41ba-829f-156c4fe8c0a0.png)

**Comment by dashie** [comment]
The same for me

**Comment by dheeraj-mishra** [comment]
What exact version are you using and do you have active consumer groups?

**Comment by garnus** [comment]
Hi, 
I didn't use the kafka dashbord for a long time but now its seams that this metric is working. 
I'm musing kafka installed from confluence ansible and kafka_exporter v1.6.0.

**Comment by y0zg** [comment]
The same, no consumer metrics. 
Can someone please update?

Using latest docker image `1.7.0` with chart https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-kafka-exporter


```
/bin/kafka_exporter --verbosity=5 --kafka.server=kafka.dev:9092 --use.consumelag.zookeeper --zookeeper.server=kafka-zookeeper.dev:2181
```

logs
```
I1128 16:16:37.940094       1 kafka_exporter.go:242] Using zookeeper lag, so connecting to zookeeper
2023/11/28 16:16:37 Connected to 172.20.142.229:2181
I1128 16:16:37.943503       1 kafka_exporter.go:264] Done Init Clients
I1128 16:16:37.944046       1 kafka_exporter.go:971] Listening on HTTP :9308
2023/11/28 16:16:37 authenticated: id=72057612588417024, timeout=4000
2023/11/28 16:16:37 re-submitting `0` credentials after reconnect
I1128 16:16:54.236403       1 kafka_exporter.go:383] Refreshing client metadata
I1128 16:16:54.289129       1 kafka_exporter.go:658] Fetching consumer group metrics
I1128 16:17:24.236557       1 kafka_exporter.go:383] Refreshing client metadata
I1128 16:17:24.311764       1 kafka_exporter.go:658] Fetching consumer group metrics
```

**Comment by bingkunyangvungle** [comment]
Hi, me too with this config:
`/bin/kafka_exporter --verbosity=5 --kafka.server=kafka.dev:9092 --use.consumelag.zookeeper --zookeeper.server=kafka-zookeeper.dev:2181`

Anyone get this one working?

**Comment by bingkunyangvungle** [comment]
Oh, it's because I'm missing the consumer group. It works.

**Comment by CodeWithAdarsha** [comment]
Good Job !

**Comment by glerma** [comment]
> Oh, it's because I'm missing the consumer group. It works.

What does this even mean?  Any more details, to help others?

**Comment by seaBFH** [comment]
add --group, if you are using cli.
```bash
kafka-console-consumer.sh \
            --consumer.config /tmp/client.properties \
            --bootstrap-server kafka.infra.svc.cluster.local:9092 \
            --topic test \
            --from-beginning \
            --group test-consumer-group
```

> > Oh, it's because I'm missing the consumer group. It works.
> 
> What does this even mean? Any more details, to help others?

**Comment by seaBFH** [comment]
It seems a common issue.  maybe add some explanation in readme.
