### ISSUE TITLE
Failed to read SASL handshake header : EOF

### ISSUE THREAD

**Issue by yanglei99** [danielqsj/kafka_exporter#36]
I need to use the following configuration to connect to my Kafka broker. (e.g. used for kafka-console-consumer.sh )

security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="xxx" password="yyy";

I hit "Failed to read SASL handshake header : EOF" when using Kafka exporter with --sasl.enabled --sasl.username=xxx --sasl.password=yyy. 

Appreciate suggestion for how to resolve the problem.

**Comment by dheerajkulakarni** [comment]
Hey @yanglei99
 
i am also getting the same error 
can I know how did you solve this issue?

Thank you

**Comment by david-pech-sestraemmy-cz** [comment]
We use similar settings for managed Oracle Cloud Streams.

Add
- --tls.enabled
- --tls.insecure-skip-tls-verify

Like this:


        - '--verbosity=100'
        - '--log.enable-sarama'
        - >-
          --kafka.server=${SERVER}:9092
        - '--sasl.enabled'
        - '--sasl.username=$(SCRAM_USERNAME)'
        - '--sasl.password=$(SCRAM_PASSWORD)'
        - '--sasl.mechanism=plain'
        - '--log.level=debug'
        - '--tls.enabled'
        - '--tls.insecure-skip-tls-verify'
