### ISSUE TITLE
How to deal with this issue:  collected metric "kafka_consumergroup_lag" { label:<name:"consumergroup" value:"group" > label:<name:"partition" value:"5" > label:<name:"topic" value:"value" > gauge:<value:4.75800766e+08 > } was collected before with the same name and label values

### ISSUE THREAD

**Issue by KD0735** [danielqsj/kafka_exporter#382]

**Comment by KD0735** [comment]
kafka_exporter doesn't work, I only find a consumer_group when I search the consumergroup has problem.

**Comment by VapZheng** [comment]
I have the same issue. Have you solved it now?

**Comment by fbm1999** [comment]
I think you can check "__consumer_offsets" this topic,  maybe there are some replicator partitions  of this topic is out of ISR and cause leader change due to some brokers has error (like disk error)
