### ISSUE TITLE
Pipeline build failing due to vulnerabilities

### ISSUE THREAD

**Issue by aadarshjain-dev** [danielqsj/kafka_exporter#439]
Hi @danielqsj

We are using **kafka_exporter** as our base image and it is generating vulnerabilities in security scan build

```
ARG REPO_LOCATION
ARG BASE_IMAGE=danielqsj/kafka-exporter
FROM ${REPO_LOCATION}${BASE_IMAGE}
```

I have already raised PR which solves this - https://github.com/danielqsj/kafka_exporter/pull/426

Can we have immediate action on this as we are blocked on releases?

**Comment by danielqsj** [comment]
Closed due to #426
