### ISSUE TITLE
New releases please.

### ISSUE THREAD

**Issue by bmm-alc** [danielqsj/kafka_exporter#453]
Hello

The kafka bitnami chart removed kafka exporter because there was no new releases since May 2023 (bitnami/charts/pull/26395).
Could it be possible to cut a release with updated dependencies ?

thanks

**Comment by abregar** [comment]
FYI since long time no tagged version, I am sharing the https://github.com/danielqsj/kafka_exporter/pull/454 as contributing the latest updates we use to keep this project secure and up to date.

**Comment by danielqsj** [comment]
Done, 1.8.0 had been released
