### ISSUE TITLE
Update prometheus server?

### ISSUE THREAD

**Issue by Karakaz** [danielqsj/kafka_exporter#59]
I am unable to add it as a datasource using both grafana 5.1.5 and 5.2.2.
All I am seeing is an error icon with no text.
![image](https://user-images.githubusercontent.com/5980958/43674359-2c1a196e-97d3-11e8-8600-2149ddeb5f49.png)

**Comment by Karakaz** [comment]
Aww, my bad. Can you link me some guide on how to do that? Thank you. Feel free to close issue.

**Comment by danielqsj** [comment]
@Karakaz Please refer to this Prometheus doc: https://prometheus.io/docs/visualization/grafana/
