### ISSUE TITLE
not able to run docker image

### ISSUE THREAD

**Issue by k92ankita** [danielqsj/kafka_exporter#67]
Hi, 

I am getting following error while trying to use docker image:

sudo docker run -ti --rm -p 9308:9308 danielqsj/kafka-exporter --kafka.server=kafka1ip:9092 --kafka.server=kafka2ip:9092 --kafka.server=kafka3ip:9092
INFO[0000] Starting kafka_exporter (version=1.2.0, branch=HEAD, revision=74450bffe4fd6df1a8c85c54bb2babb7506ac7fc)  source="kafka_exporter.go:423"
INFO[0000] Build context (go=go1.9, user=travis@travis-job-999c3d4e-5314-489c-97c2-b78ee2befa68, date=20181008-03:07:38)  source="kafka_exporter.go:424"
panic: runtime error: index out of range

goroutine 1 [running]:
main.main()
        /home/travis/gopath/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:429 +0x520c

can you please help?
go version: go version go1.9.3 linux/amd64

**Comment by wakeful** [comment]
can you share your `docker-compose` file? did you check that you can resolve `kafka3ip` from inside the container?

**Comment by skiloop** [comment]
this is a arguments parsing error, default value for kafka.labels make it failed to split

**Comment by mkaranasou** [comment]
👍

**Comment by StephanX** [comment]
this latest update breaks for me.  Have reverted to v1.2.0 for now.

`> ku logs -f p8s-kafka-exporter-579fd7f7d8-xt2wb    

time="2018-10-24T15:53:49Z" level=info msg="Starting kafka_exporter (version=1.2.0, branch=HEAD, revision=74450bffe4fd6df1a8c85c54bb2babb7506ac7fc)" source="kafka_exporter.go:423"
time="2018-10-24T15:53:49Z" level=info msg="Build context (go=go1.9, user=travis@travis-job-999c3d4e-5314-489c-97c2-b78ee2befa68, date=20181008-03:07:38)" source="kafka_exporter.go:424"
panic: runtime error: index out of range

goroutine 1 [running]:
main.main()
	/home/travis/gopath/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:429 +0x520c
`

**Comment by danielqsj** [comment]
thanks @skiloop , merged PR.
Closed this issue, if problem still existing, we can reopen it.
