### ISSUE TITLE
Noticed Abnormal GC/Memory Usage

### ISSUE THREAD

**Issue by jbkc85** [danielqsj/kafka_exporter#7]
All three lines represent the residential memory size reported (process_resident_memory_bytes{}) from the same environment/cluster.  Not sure why in certain cases, it regulates itself and in others it does not.  I am looking further into it, but wanted to share the current situation just in case anyone had any insight.

4w time period: process_resident_memory_bytes{}

![screen shot 2018-01-10 at 10 25 06 am](https://user-images.githubusercontent.com/215878/34783218-9858f698-f5f0-11e7-9177-7f01d489a8dc.png)

**Comment by jbkc85** [comment]
forgot: All v0.3.0 updated on Dec 6th.

**Comment by danielqsj** [comment]
Interesting.

**Comment by jbkc85** [comment]
After updating, all exporters are slowly gaining residential memory.  I am still researching/investigating to see if i can pinpoint it to a specific function, variable, etc, but want to keep you updated in case another issue crops up.

I know I originally jumped on the chat to mention the new topics not being found in Kafka after starting the exporter - do you think this could have something to do with the implementation of the metadata refresh?

**Comment by shuz** [comment]
Feels there is memory/fd leak.
```
2018/02/26 23:38:12 http: Accept error: accept tcp [::]:9308: accept4: too many open files; retrying in 20ms
2018/02/26 23:38:12 http: Accept error: accept tcp [::]:9308: accept4: too many open files; retrying in 40ms
2018/02/26 23:38:12 http: Accept error: accept tcp [::]:9308: accept4: too many open files; retrying in 80ms
2018/02/26 23:38:12 http: Accept error: accept tcp [::]:9308: accept4: too many open files; retrying in 160ms
```

**Comment by jbkc85** [comment]
definitely noticing the same thing as @shuz mentioned - though i am actively monitoring it and restarting it before it gets too troublesome:

![screen shot 2018-03-06 at 9 11 05 am](https://user-images.githubusercontent.com/215878/37039985-668718bc-211e-11e8-84e3-9e02c66f54ee.png)

```
groups:
  - name: ExporterAlerts
    rules:
      - alert: HighResidentMemory
        expr: |
          process_resident_memory_bytes{ job="kafka_exporter" }
          > 78643200
        for: 1m
        labels:
          severity: info
        annotations:
          description: "[INFO] {{ $labels.hostname }} kafka_exporter is exceeding the threshold for resident memory in bytes."
```
Occurrences are higher on Kafka nodes with heavier use (more metric changes in kafka_exporter)

**Comment by danielqsj** [comment]
@jbkc85 @shuz Thanks, I will checking this issue.

**Comment by Techcadia** [comment]
We are even seeing more aggressive memory usage currently consuming 1GB at max before OOM kicks in and kills the process.

**Comment by maxtar** [comment]
And in our case we get 
```
←[31mERRO←[0m[2472] Can't get member assignment of group: connect-cluster: kafka
: insufficient data to decode packet, more bytes expected  ←[31msource←[0m="kafk
a_exporter.go:370"
```
Is it correct behavior?

**Comment by jbkc85** [comment]
@danielqsj i noticed that there was a commit recently that was titled 'fixed memory leak'.  If this is the case, is there an upcoming release so we can give it a test?  I don't mind making my own binary, but would prefer to have an actual release to test out and point to :-)

**Comment by danielqsj** [comment]
@jbkc85 @shuz @Techcadia @maxtar 
v1.1.0 is released. Please try new image.

**Comment by maxtar** [comment]
This release work for us. Exporter consuming about 20Mb.

**Comment by danielqsj** [comment]
@maxtar Glad to hear that.

**Comment by jbkc85** [comment]
![screen shot 2018-04-13 at 8 34 02 am](https://user-images.githubusercontent.com/215878/38737645-7dfc3b40-3ef5-11e8-9a2f-2c7e0abab58c.png)


👍

**Comment by jbkc85** [comment]
will keep an eye on things and re-open if necessary, but looks good at the moment!
