### ISSUE TITLE
sasl.username/password requirement in default,  can't see lag in metrics

### ISSUE THREAD

**Issue by vladimir4862** [danielqsj/kafka_exporter#8]
Hello i found 2 issues in v 1.0

1) 
kafka_exporter requirements sasl.username/password without sasl.enabled. 

for avoid it i just add this in running line 
 --sasl.username=" " --sasl.password=" "  (with empty string) 

2) i can't see lag in metrics, and can't understood why. 
in my exporter isn't there metrics 
kafka_consumergroup_current_offset	
kafka_consumergroup_lag

kafka 0.10.2.1
kafka-exporter 1.0.0
command line for run: 
kafka_exporter  --kafka.server=localhost:9092 --log.level="debug" --sasl.username=" " --sasl.password=" "

**Comment by lovelyCoder** [comment]
I use 1.0.0 and start with command ./kafka_exporter --web.listen-address=:9308 --kafka.server=*****
I also cat't see the metric kafka_consumergroup_lag

**Comment by danielqsj** [comment]
@vladimir4862 @lovelyCoder Ack, I will check it.

**Comment by danielqsj** [comment]
@vladimir4862 @lovelyCoder 
Are your consumer groups active? Currently, Kafka Protocal only support active consumer group.

**Comment by danielqsj** [comment]
@vladimir4862 Question 1 has been fixed in v1.0.1. Pls try new version.

**Comment by vladimir4862** [comment]
1) thanks a lot, 
2) you are right, metrics with activity are displayed

**Comment by danielqsj** [comment]
@vladimir4862 Great.
