### ISSUE TITLE
Flag for exclusion of certain groups/topics

### ISSUE THREAD

**Issue by jorgelbg** [danielqsj/kafka_exporter#91]
The exporter at this moment provides the option to filter groups & filters (`topic.filter` and `group.filter` flags) using a regular expression. Unfortunately, this can only be used to collect *matching* groups/filters. There is no option to *only exclude* certain topics. This happens because the Go's regex library doesn't support negative look-ahead (see https://groups.google.com/forum/m/#!topic/golang-nuts/7qgSDWPIh_E). 

One option would be to use a different regex library, but that would mean to also potentially change the format of the regex, which would break backward compatibility. We could for instance use: https://github.com/dlclark/regexp2.

Another option could be to add a `filter.exclude` (temporary name) boolean flag that *toggles* the matching logic (include vs exclude). This would allow to either include or exclude  all that matches the specified regexes.

Both options have pros & cons, the advantage of using regexp2 would be that there is less logic to maintain in the exporter (the positive/negative matching will be handled in the regexp2 engine). The other option adds an tiny bit of code to the exporter.

I would like to hear some opinion on this.

**Comment by danielqsj** [comment]
thanks, closed by https://github.com/danielqsj/kafka_exporter/pull/379
