### ISSUE TITLE
Faced with "Is your cluster reachable?" error while can consume messages from kafka-console-consumer.sh

### ISSUE THREAD

**Issue by nikita-clearscale** [danielqsj/kafka_exporter#94]
The command is:

    docker run -ti --rm -p 9308:9308 danielqsj/kafka-exporter --kafka.server=ip-XX-XXX-X-XX.us-west-1.compute.internal:9092

Leads to:

    INFO[0000] Starting kafka_exporter (version=1.2.0, branch=HEAD, revision=56c1d47f9794d59d042852cc31558257e24d2ea0)  source="kafka_exporter.go:500"
    INFO[0000] Build context (go=go1.9, user=travis@travis-job-fa00a602-ae4f-4696-ac19-3ee24885c116, date=20190131-13:51:26)  source="kafka_exporter.go:501"
    ERRO[0000] Error Init Kafka Client                       source="kafka_exporter.go:184"
    panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

    goroutine 1 [running]:
    main.NewExporter(0xc420047d20, 0x1, 0x1, 0x100, 0x96d438, 0x0, 0x96d438, 0x0, 0x0, 0x96d438, ...)
        /home/travis/gopath/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:185 +0xbbc
    main.main()
        /home/travis/gopath/src/github.com/danielqsj/kafka_exporter/kafka_exporter.go:606 +0x3aa7

I have added any variants of `XX-XXX-X-XX` to `/etc/hosts` like that:

    XX.XXX.X.XX kafkaHost
    XX.XXX.X.XX kafkaHost.us-west-1a.somehost.net
    XX.XXX.X.XX ip-XX-XXX-X-XX.us-west-1.compute.internal

But this did not help.

Please note that I am able to consume kafka messages via kafka-console-consumer.sh, e.g. the following works:

    bash kafka-console-consumer.sh --bootstrap-server ip-XX-XXX-X-XX.us-west-1.compute.internal:9092 --topic mytopic

E.g. kafka and topic are reachable, but can not be found by exporter. Please help or give a direction how to figure out the problem.

**Comment by nikita-clearscale** [comment]
Addiung paramter for docker command like  `--dns YY.YY.YYY.Y --dns-search kafkaHost.us-west-1a.somehost.net` solved my issue. (`YY.YY.YYY.Y` - dns IP address provided by aws)

**Comment by Basma1912** [comment]
--dns is no longer a known flag and I am getting the same error
